### ISSUE TITLE
README uses incorrect grammar.

### ISSUE THREAD

**Issue by ooliver1** [cwz6h/discord-bot-24-7-hosting-free#1]
> First, Click "Use This Template" Set The Repository Visibillity To Public And Enter A Name For Your Repo And Click The Create Button.

No language starts every word with a capital letter. This is not even title case as words such as `the` are capitalised Instead it should be like:

> First, click "Use This Template", set the repository visibility to public and enter a name for your respository and click the create button.

**Comment by cwz6h** [comment]
fixed
