### ISSUE TITLE
README treats GPL as a legal contract

### ISSUE THREAD

**Issue by ooliver1** [cwz6h/discord-bot-24-7-hosting-free#2]
> Fuck You. Skid Something Else, Because This Repo Has A GPL License.

The GPL license is not a "get out of jail free card" you use against bad actors as a "haha you can't do that". You have no liability due to the license. This treats it as a legally binding contract, which github itself says:

![github displaying the guidelines of the GPL license](https://user-images.githubusercontent.com/34910574/185803208-2eeba35d-856c-4645-8a42-b58c7504f604.png)

**Comment by cwz6h** [comment]
alright i changed the readme jeez
