### ISSUE TITLE
Huge code duplication of workflows

### ISSUE THREAD

**Issue by ooliver1** [cwz6h/discord-bot-24-7-hosting-free#4]
`start.yml` repeats the same steps with the **same** comments so many times, this is unnecessary. You can use [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows), [the matrix strategy](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) with placeholders, a list of numbers will do fine over entire duplication.

**Comment by cwz6h** [comment]
It is necessary. Because one job can run for 6 hours. The bot will die in 6 hours. Since Im Using 140 Jobs The Bot Will Die in 35 Days Then Run Again. I may look at this issue later to improve this method of 24/7 hosting bots. MAYBE
