### ISSUE TITLE
`start.sh` does not use a shebang

### ISSUE THREAD

**Issue by ooliver1** [cwz6h/discord-bot-24-7-hosting-free#5]
[Shebangs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) are used for non-binary executables, telling the shell what to use to run the file. This would remove the `bash` part from the workflow whilst also being best practice.

**Comment by cwz6h** [comment]
First off its setup.sh. And second is that the code works fine
