### ISSUE TITLE
Extremely inconsistent formatting

### ISSUE THREAD

**Issue by ooliver1** [cwz6h/discord-bot-24-7-hosting-free#7]
[main.py](https://github.com/cwz6h/discord-bot-24-7-hosting-free/blob/main/main.py) does not follow [PEP8](https://peps.python.org/pep-0008/) in the slightest. `'`, 2 indents, inconsistent keyword argument usage, different module imports on the same line etc.

**Comment by cwz6h** [comment]
bruh its just a main.py bot start template
